# Generated by Django 5.1 on 2024-08-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='chat_id',
            field=models.CharField(unique=True),
        ),
    ]
