# Generated by Django 5.1 on 2024-08-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog_text', models.CharField()),
                ('number_likes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
