# Generated by Django 5.1 on 2024-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.png', upload_to='thumbnails/'),
        ),
    ]
